### ISSUE TITLE
Fresh install, Server -> Config, error

### ISSUE THREAD

**Issue by xinux87** [Joe-Klauza/sandstorm-admin-wrapper#118]
HI all, 

With a new clean install i'm getting this error: 

As if the Game.ini file dosent exist..

![image](https://user-images.githubusercontent.com/6419184/133925856-35170917-bc8a-4ed0-9360-88e1dbd149df.png)

Thanks!!

An error occurred (Errno::ENOENT). Only hosts can see the following message and backtrace: No such file or directory @ rb_sysopen - /home/sandstorm/server-config/a62789e1-c334-48c3-875d-273c410c9bb1/Game.ini | Backtrace:
~/admin-interface/lib/webapp.rb:739:in `read'
~/admin-interface/lib/webapp.rb:739:in `block in <class:SandstormAdminWrapperSite>'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `call'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (3 levels) in route!'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (2 levels) in route!'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `each'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
/usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
/usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
/usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
/usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
/usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
/usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
/usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
/usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/handler/webrick.rb:95:in `service'
/usr/local/lib/ruby/2.7.0/webrick/httpserver.rb:140:in `service'
/usr/local/lib/ruby/2.7.0/webrick/httpserver.rb:96:in `run'
/usr/local/lib/ruby/2.7.0/webrick/server.rb:307:in `block in start_thread'

**Comment by xinux87** [comment]
After the installation, yout should go to Wrapper -> Config  and update the wrapper and restart the wrapper to work propertly.
