### ISSUE TITLE
Server -> Config fails with Ruby stack trace with Docker

### ISSUE THREAD

**Issue by CraigChilds94** [Joe-Klauza/sandstorm-admin-wrapper#122]
When running this application using the provided `Dockerfile` I'm presented with the following stacktrace when I navigate to `Server -> Config`

It looks as though there's an issue with missing gems.

```
An error occurred (Errno::ENOENT). Only hosts can see the following message and backtrace: No such file or directory @ rb_sysopen - /home/sandstorm/server-config/db50cbf3-143e-4030-8929-dd1ac2171d92/Game.ini | Backtrace:
~/admin-interface/lib/webapp.rb:739:in `read'
~/admin-interface/lib/webapp.rb:739:in `block in <class:SandstormAdminWrapperSite>'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `call'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (3 levels) in route!'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (2 levels) in route!'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `each'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
/usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
/usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
/usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
/usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
/usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
/usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
/usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
/usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/handler/webrick.rb:95:in `service'
/usr/local/lib/ruby/2.7.0/webrick/httpserver.rb:140:in `service'
/usr/local/lib/ruby/2.7.0/webrick/httpserver.rb:96:in `run'
/usr/local/lib/ruby/2.7.0/webrick/server.rb:307:in `block in start_thread'
```

**Comment by Joe-Klauza** [comment]
For some reason the Game.ini for the config wasn't generated properly, so when SAW goes to read the file it can't be found (ENOENT). I'd suggest restarting SAW, and if that doesn't help check that the user running SAW has permissions for the directories and files in `/home/sandstorm/`... I'd recommend running this within a contained subdirectory like `/home/sandstorm/sandstorm-admin-wrapper` to avoid polluting the `sandstorm` user's home directory. If you already have one, that might be a clue as to why this is failing. 🤔

**Comment by CraigChilds94** [comment]
Okay thank you! It's probably worth updating the docker stuff to be in a working state :)
