### ISSUE TITLE
openssl and httpresponse error

### ISSUE THREAD

**Issue by alphatonic** [Joe-Klauza/sandstorm-admin-wrapper#123]
The server runs seemingly normally (connection, rcon and query status is up) but these error pop up in the terminal.

This sounds like my firewall is blocking something but sandstorm is allowed already.

`2022-01-10 11:28:27 +0100 | ERROR   | An established connection was aborted by the software in your host machine.`

and then there's this error.

```
2022-01-10 11:28:27 +0100 | ERROR   | Backtrace:
  d:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/openssl-2.2.0/lib/openssl/buffering.rb:345:in `syswrite'
  d:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/openssl-2.2.0/lib/openssl/buffering.rb:345:in `do_write'
  d:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/openssl-2.2.0/lib/openssl/buffering.rb:362:in `block in write'
  d:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/openssl-2.2.0/lib/openssl/buffering.rb:361:in `each'
  d:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/openssl-2.2.0/lib/openssl/buffering.rb:361:in `inject'
  d:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/openssl-2.2.0/lib/openssl/buffering.rb:361:in `write'
  d:/Ruby26-x64/lib/ruby/2.6.0/webrick/httpresponse.rb:439:in `copy_stream'
  d:/Ruby26-x64/lib/ruby/2.6.0/webrick/httpresponse.rb:439:in `send_body_io'
  d:/Ruby26-x64/lib/ruby/2.6.0/webrick/httpresponse.rb:313:in `send_body'
  d:/Ruby26-x64/lib/ruby/2.6.0/webrick/httpresponse.rb:212:in `send_response'
  d:/Ruby26-x64/lib/ruby/2.6.0/webrick/httpserver.rb:112:in `run'
  d:/Ruby26-x64/lib/ruby/2.6.0/webrick/server.rb:307:in `block in start_thread'
```

**Comment by Joe-Klauza** [comment]
I'm not certain if this is the issue, but your firewall may be blocking the SAW TCP port (defined in config.toml or on the Wrapper Config page within SAW).

**Comment by alphatonic** [comment]
I forwarded that port too and the error is gone. Thank you.
